# 网站设置
title: 我的技术与阅读分享
description: 分享AI使用技巧、网络技术、观影感悟与读书笔记
baseurl: ""  # 如果是项目站点需要设置为 "/项目名"
url: ""  # 你的GitHub Pages URL

# 作者信息
author:
  name: 你的名字
  email: your-email@example.com

# 构建设置
markdown: kramdown
permalink: /:categories/:title/
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

# 分页设置
paginate: 6
paginate_path: "/blog/page:num/"

# 集合设置
collections:
  ai_tips:
    output: true
    permalink: /ai-tips/:title/
  tech_posts:
    output: true
    permalink: /tech/:title/
  movie_reviews:
    output: true
    permalink: /movies/:title/
  book_notes:
    output: true
    permalink: /books/:title/

# 默认布局设置
defaults:
  - scope:
      path: ""
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "ai_tips"
    values:
      category: "AI技巧"
  - scope:
      path: ""
      type: "tech_posts"
    values:
      category: "网络技术"
  - scope:
      path: ""
      type: "movie_reviews"
    values:
      category: "观影感悟"
  - scope:
      path: ""
      type: "book_notes"
    values:
      category: "读书笔记"
